### ISSUE TITLE
Remove node_module folder from repo

### ISSUE THREAD

**Issue by scifisatan** [turttlehouse/BudgetSathi-NodeJS#1]
As there are difference in dependencies required to run and dependencies during development, node modules are not pushed to repo.  Also, they make your repo bloated with unnecessary dependencies you installed during development, so it is best practice to not push node-module folder. Use .gitignore to prevent it from happening. And for users, they can always install required dependencies using `npm i` command as mentioned in your readme.

**Comment by turttlehouse** [comment]
Thank you for raising the concern regarding the `node_modules` folder in the repository. I've taken your feedback into consideration and have now removed the `node_modules` folder from the repository. This should help reduce the repository size and improve its cleanliness.

If you have any further questions or concerns, please feel free to ask. Your feedback is valuable to me.
